services:
  jupyter:
    image: jupyter
    user: root
    ports:
      - 8889:8888
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./datasets:/home/jovyan/datasets
    command: start-notebook.py --NotebookApp.token=${ACCESS_TOKEN}
